Repository prgrms-web-devcourse/Team-6Jeans-Hype-FE, pull requests merged in 2023-03, with the labels that each got.

#69 refactor: 추천 피드, 글 상세 및 대결 신청 페이지 공통 컴포넌트 적용
  public/images/back-deepblue-icon.svg
  public/images/back-white-icon.svg
  public/images/circle-play.png
  public/images/fire.png
  public/images/full-heart.png
  public/images/heart.png
  public/images/prev-button.png
  public/images/white-fire.png
  public/images/white-full-heart.png
  src/components/common/BottomNav/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/ImageButtons/BattleButton.tsx
  src/components/common/ImageButtons/LikeButton.tsx
  src/components/post/battle/index.tsx
  src/components/post/detail/index.tsx
  src/components/post/detail/musicInfo/index.tsx
  src/components/post/index.tsx
Labels: :hammer:Refactor

#73 refactor: svg 변경, styled-component명 수정, COLOR 변수로 수정
  public/images/down-arrow-gray.svg
  public/images/down-arrow.png
  public/images/down-arrow.svg
  public/images/up-arrow.svg
  src/components/post/battle/index.tsx
  src/components/post/battle/mybattleList/index.tsx
  src/components/post/detail/index.tsx
  src/components/post/detail/musicInfo/index.tsx
  src/components/post/index.tsx
Labels: :hammer:Refactor

#86 fix: 로그인 콜백 뷰 > 토큰이 전달 됐음에도 불구하고 잠시 에러 화면이 노출되는 버그 fix
  src/components/login/utils/localStorage.ts
  src/pages/auth/callback/google.tsx
Labels: :lady_beetle:BugFix

#79 feat: API 연결해서 데이터 받아오기
  src/components/common/Battles/index.tsx
  src/components/post/api.ts
  src/components/post/battle/api.ts
  src/components/post/battle/index.tsx
  src/components/post/battle/mybattleList/api.ts
  src/components/post/battle/mybattleList/index.tsx
  src/components/post/battle/types.ts
  src/components/post/detail/api.ts
  src/components/post/detail/index.tsx
  src/components/post/detail/musicInfo/index.tsx
  src/components/post/detail/types.ts
  src/components/post/index.tsx
  src/components/post/types.ts
  src/pages/post/battle/mybattlelist/index.tsx
Labels: :sparkles:Feature

#94 refactor: 추천 피드, 추천 상세 페이지, 대결 신청 페이지 type 수정
  src/components/common/BattleMusicInfo/index.tsx
  src/components/post/battle/api.ts
  src/components/post/battle/index.tsx
  src/components/post/battle/mybattleList/api.ts
  src/components/post/battle/mybattleList/index.tsx
  src/components/post/battle/types.ts
  src/components/post/detail/api.ts
  src/components/post/detail/index.tsx
  src/components/post/detail/musicInfo/index.tsx
  src/components/post/index.tsx
  src/components/post/types.ts
Labels: :hammer:Refactor

#96 Feat/#83 my page markup
  public/images/default-profile.svg
  public/images/history.svg
  public/images/point.svg
  public/images/rank.svg
  src/components/common/BottomNav/index.tsx
  src/components/mypage/ResultCard.tsx
  src/components/mypage/UserHeader.tsx
  src/pages/mypage/index.tsx
  src/styles/global.ts
  src/styles/reset.ts
Labels: :sparkles:Feature

#97 refactor: 전체적인 디자인 및 문제 손보기
  src/components/battle/select/index.tsx
  src/components/battle/voteResult/index.tsx
  src/components/common/BattleMusicInfo/index.tsx
  src/components/common/Genres/index.tsx
  src/components/common/Header/index.tsx
Labels: :hammer:Refactor

#98 fix: hotfix
  src/components/common/Genres/index.tsx
  src/components/post/api.ts
  src/components/post/create/SelectedMusic.tsx
  src/components/post/create/index.tsx
  src/components/post/detail/index.tsx
  src/components/post/index.tsx
  src/hooks/useCreatePost.ts
Labels: :lady_beetle:BugFix

#106 feat: api 사용자 로그인데이터 사용되도록 변경
  src/components/post/api.ts
Labels: :hammer:Refactor

#107 fix: 로그인 인증 토큰 수정
  src/components/login/store.ts
Labels: :lady_beetle:BugFix

#100 feat: 특정 기능은 인증된 사용자만 클릭할 수 있게 하는 hook 구현 + 바텀 네브바 '추천' 버튼에 적용
  src/components/common/BottomNav/index.tsx
  src/components/common/Modal/Confirm.tsx
  src/components/common/Modal/Wrapper.tsx
  src/components/login/AuthRequiredModal.tsx
  src/components/login/store.ts
  src/components/login/useAuth.ts
  src/pages/_app.tsx
Labels: :sparkles:Feature

#116 featur: 대결 투표 api연결
  src/components/battle/api.ts
  src/components/battle/select/index.tsx
  src/components/battle/temp_dummy.js
  src/components/battle/types.ts
  src/components/battle/voteResult/index.tsx
  src/components/common/BattleMusicInfo/index.tsx
  src/components/common/skeleton/AlbumPoster.tsx
  src/components/post/battle/index.tsx
  src/components/post/battle/mybattleList/index.tsx
  src/components/post/battle/types.ts
  src/components/post/types.ts
  src/hooks/useVoteResult.ts
Labels: :sparkles:Feature, :hammer:Refactor

#113 feat: 재생 버튼 공통 컴포넌트 구현
  public/images/play-button.svg
  src/components/common/MusicPlayButton/index.tsx
  src/components/post/detail/index.tsx
Labels: :sparkles:Feature

#104 feat: 대결 신청 기능 구현
  src/components/battle/types.ts
  src/components/common/BattleMusicInfo/index.tsx
  src/components/common/ConfirmModal/index.tsx
  src/components/post/battle/api.ts
  src/components/post/battle/index.tsx
  src/components/post/battle/mybattleList/api.ts
  src/components/post/battle/mybattleList/index.tsx
  src/components/post/battle/types.ts
  src/hooks/useConfirmModal.ts
  src/pages/post/battle/index.tsx
Labels: :sparkles:Feature

#127 refactor: RecommendationPost 공통 컴포넌트 생성
  src/components/common/AlbumPoster/index.tsx
  src/components/common/ImageButtons/LikeButton.tsx
  src/components/common/RecommendationPost/index.tsx
  src/components/post/detail/index.tsx
  src/components/post/index.tsx
  src/components/post/types.ts
Labels: :hammer:Refactor

#124 feat: 대결 투표 상세보기 화면 만들기
  public/images/go-to-shuffle-icon.svg
  src/components/battle/api.ts
  src/components/battle/select/index.tsx
  src/components/battle/voteResult/index.tsx
  src/components/post/battle/types.ts
  src/hooks/useVoteResult.ts
  src/pages/battle/detail/index.tsx
Labels: :sparkles:Feature, :hammer:Refactor

#131 fix: axiosInstance 디폴트 헤더에 토큰 값 유지되도록
  src/components/login/store.ts
Labels: :lady_beetle:BugFix

#133 feat: 대결 리스트 페이지 마크업
  public/images/no-background-logo.svg
  public/images/shuffle.svg
  src/components/battle/Card.tsx
  src/components/battle/list/types.ts
  src/pages/battle/list.tsx
  src/pages/battle/short/index.tsx
Labels: :sparkles:Feature

#119 feat: 추천 피드 세부 기능 구현
  src/components/common/ImageButtons/BattleButton.tsx
  src/components/common/ImageButtons/LikeButton.tsx
  src/components/post/index.tsx
  src/pages/post/index.tsx
Labels: :sparkles:Feature

#123 feat: 추천 글 상세페이지 세부 기능 구현
  src/components/post/detail/index.tsx
  src/components/post/detail/musicInfo/index.tsx
  src/components/post/detail/types.ts
Labels: :sparkles:Feature

#135 feat: 마이페이지 내 목록 공통 컴포넌트 생성
  public/images/arrow-right.svg
  src/components/common/AlbumPoster/index.tsx
  src/components/common/RecommendationPost/index.tsx
  src/components/mypage/ContentList.tsx
  src/components/mypage/UserContent.tsx
  src/components/mypage/UserHeader.tsx
  src/components/mypage/api.ts
  src/components/mypage/types.ts
  src/pages/mypage/index.tsx
Labels: :sparkles:Feature

#126 feat: 대결 신청 페이지 세부 기능 구현
  src/components/common/BattleMusicInfo/index.tsx
  src/components/common/MusicPlayButton/index.tsx
  src/components/post/battle/index.tsx
  src/components/post/battle/mybattleList/index.tsx
Labels: :sparkles:Feature

#138 chore: axiosInstance에 baseURL 적용
  src/api/index.ts
  src/components/battle/api.ts
  src/components/post/api.ts
  src/components/post/battle/api.ts
  src/components/post/battle/mybattleList/api.ts
  src/components/post/detail/api.ts
Labels: ✏️Chore

#136 chore: 장르 비활성화 옵션 추가
  src/components/common/Genres/index.tsx
Labels: ✏️Chore

#132 refactor: 대결 투표 api
  src/components/battle/api.ts
  src/components/battle/select/index.tsx
  src/components/post/api.ts
  src/components/post/battle/api.ts
  src/components/post/battle/types.ts
  src/hooks/useVoteResult.ts
Labels: :hammer:Refactor

#145 feat: 마이페이지 유저 정보 API 연결
  src/components/mypage/ResultCard.tsx
  src/components/mypage/UserHeader.tsx
  src/components/mypage/api.ts
  src/components/mypage/types.ts
Labels: :sparkles:Feature

#148 fix: 잘못 들어간 api path 수정
  src/components/post/detail/api.ts
Labels: :lady_beetle:BugFix

#146 feat: 장르 선택 기능 추가
  src/components/battle/api.ts
  src/components/battle/select/index.tsx
  src/components/battle/temp_dummy.js
  src/hooks/useGenre.ts
  src/hooks/useVoteResult.ts
Labels: :sparkles:Feature

#154 fix: 대결 리스트 페이지 > 바텀 네브바 만큼의 바텀 패딩 추가
  src/pages/battle/list.tsx
Labels: :lady_beetle:BugFix

#160 fix: 건너뛰기 알고리즘 수정
  src/components/battle/api.ts
  src/components/common/BattleMusicInfo/index.tsx
Labels: :lady_beetle:BugFix

#162 refactor: 이미지 가운데 정렬 넣기
  src/components/common/BattleMusicInfo/index.tsx
Labels: :hammer:Refactor

#163 refactor: skeleton 추가
  src/components/battle/select/index.tsx
  src/components/common/Genres/index.tsx
  src/components/common/skeleton/AlbumPosterSkeleton.tsx
  src/components/common/skeleton/GenreSkeleton.tsx
  src/components/common/skeleton/MusicListSkeleton.tsx
  src/components/post/SearchMusics/MusicList.tsx
  src/components/post/battle/mybattleList/index.tsx
  src/components/post/create/index.tsx
  src/components/post/index.tsx
Labels: :hammer:Refactor

#167 fix: PostDetailContent 개선
  src/components/post/detail/index.tsx
Labels: :hammer:Refactor

#151 feat: 마이페이지 대결 목록 API 연결
  src/components/common/RecommendationPost/index.tsx
  src/components/mypage/UserContent.tsx
  src/components/mypage/api.ts
  src/components/mypage/types.ts
  src/components/post/battle/index.tsx
Labels: :sparkles:Feature

#174 fix: 추천 피드 목록 이벤트 버블링 막기
  src/components/common/RecommendationPost/index.tsx
Labels: :lady_beetle:BugFix

#168 feat: 로그인이 필요한 페이지인 경우 로그인 강제하기
  .github/.env
  src/components/login/AuthRequiredPage.tsx
  src/pages/mypage/battle/index.tsx
  src/pages/mypage/index.tsx
  src/pages/post/battle/index.tsx
  src/pages/post/create.tsx
  src/pages/post/searchMusics.tsx
Labels: :sparkles:Feature

#181 fix: 대결 shorts, 상세 페이지에서 음악 재생 안되는 버그 해결
  src/components/common/BattleMusicInfo/index.tsx
  src/components/common/Modal/Wrapper.tsx
  src/components/common/MusicPlayButton/index.tsx
Labels: :lady_beetle:BugFix

#182 refactor: 추천 피드 리팩토링
  src/components/post/api.ts
  src/components/post/index.tsx
Labels: :hammer:Refactor

#183 feat: 유저 랭킹 페이지 만들기
  src/components/ranking/RankingCard.tsx
  src/components/ranking/api.ts
  src/components/ranking/index.tsx
  src/components/ranking/types.ts
  src/pages/index.tsx
  src/pages/ranking/index.tsx
Labels: :sparkles:Feature

#186 feat: 대결 리스트 페이지 장르 필터링 구현
  src/components/battle/list/api.ts
  src/components/battle/list/constants.ts
  src/components/battle/list/hooks/useGetBattles.ts
  src/components/battle/list/types.ts
  src/pages/battle/list.tsx
Labels: :sparkles:Feature

#178 chore: 대결 상세 페이지 pause 아이콘 및 스타일 수정
  public/images/pause-button.svg
  public/images/play-button.svg
  src/components/common/Header/index.tsx
  src/components/common/MusicPlayButton/index.tsx
  src/components/post/detail/index.tsx
  src/components/post/detail/musicInfo/index.tsx
Labels: ✏️Chore

#189 feat: 대결 목록 더보기 라우팅
  src/components/mypage/ContentList.tsx
Labels: :sparkles:Feature

#188 refactor: 대결 투표 리팩토링
  src/components/battle/api.ts
  src/components/battle/select/index.tsx
  src/components/battle/types.ts
  src/components/battle/voteResult/index.tsx
  src/components/common/BattleMusicInfo/index.tsx
  src/components/common/Genres/index.tsx
  src/components/common/skeleton/GenreSkeleton.tsx
  src/hooks/useVoteResult.ts
Labels: :hammer:Refactor

#197 feat: 대결 피드 페이지 status 필터링 구현
  src/components/battle/constants.ts
  src/components/battle/list/api.ts
  src/components/battle/list/hooks/useGetBattles.ts
  src/components/battle/list/index.tsx
  src/components/battle/types.ts
  src/components/common/Filter.tsx
  src/components/common/Genres/index.tsx
  src/pages/battle/list.tsx
  src/styles/reset.ts
Labels: :sparkles:Feature

#198 refactor: 랭킹페이지 디자인 수정
  src/components/common/Header/index.tsx
  src/components/ranking/RankingCard.tsx
  src/components/ranking/index.tsx
  src/styles/global.ts
Labels: :hammer:Refactor

#203 feat: 랭킹 페이지 api 연동
  src/components/ranking/api.ts
Labels: :sparkles:Feature

#204 fix: 로그인 안 한 유저 막기
  src/components/common/ImageButtons/BattleButton.tsx
  src/components/common/ImageButtons/LikeButton.tsx
Labels: :lady_beetle:BugFix

#195 feat: 마이페이지 NoContent 적용
  src/components/common/Genres/index.tsx
  src/components/common/Header/index.tsx
  src/components/common/NoContent/index.tsx
  src/components/mypage/ContentList.tsx
  src/components/mypage/UserContent.tsx
  src/components/post/SearchMusics/SearchInput.tsx
  src/components/post/SearchMusics/index.tsx
  src/components/post/battle/index.tsx
  src/components/post/detail/index.tsx
  src/components/ranking/RankingCard.tsx
  src/pages/battle/detail/index.tsx
  src/pages/battle/list.tsx
  src/pages/mypage/battle/index.tsx
  src/styles/global.ts
Labels: :sparkles:Feature

#199 refactor: 대결 신청 페이지 리팩토링
  src/components/post/battle/index.tsx
  src/components/post/battle/mybattleList/api.ts
  src/components/post/battle/mybattleList/index.tsx
Labels: :hammer:Refactor

#208 feat: 대결 리스트에서 끝난 대결은 흑백으로 보이도록
  src/components/battle/Card/Finished.tsx
  src/components/battle/Card/index.tsx
  src/components/battle/Card/style.ts
  src/components/battle/list/api.ts
  src/components/battle/list/index.tsx
  src/components/battle/list/types.ts
  src/components/mypage/UserContent.tsx
  src/components/mypage/battle/api.ts
  src/components/mypage/battle/useGetMyBattleList.ts
Labels: :sparkles:Feature

#207 feat: 장르별 좋아요 순으로 정렬 된 추천 글 render
  package.json
  src/components/main/GenreTop10Post/api.ts
  src/components/main/GenreTop10Post/index.tsx
  src/components/main/GenreTop10Post/type.ts
  src/pages/index.tsx
  yarn.lock
Labels: :sparkles:Feature

#209 fix: 사소한 스타일 버그 fix (회원가입 및 추천 상세 페이지, 필터)
  src/components/common/Filter.tsx
  src/components/post/detail/index.tsx
  src/pages/login.tsx
Labels: :lady_beetle:BugFix

#222 fix: 쓸모 없는 refetch 없애기
  src/pages/battle/list.tsx
Labels: :lady_beetle:BugFix

#220 chore: recommendationPost username 추가
  src/components/common/ImageButtons/BattleButton.tsx
  src/components/common/RecommendationPost/index.tsx
  src/components/post/index.tsx
Labels: ✏️Chore

#212 fix: post/battle Header 스타일 수정
  src/components/post/battle/index.tsx
  src/styles/global.ts
Labels: :lady_beetle:BugFix

#229 refactor: 추천 피드 리팩토링
  src/components/common/BattleMusicInfo/index.tsx
  src/components/post/SearchMusics/MusicList.tsx
  src/components/post/battle/mybattleList/index.tsx
  src/components/post/index.tsx
  src/pages/login.tsx
Labels: :hammer:Refactor

#235 refactor: svg 파일 import 해서 사용
  src/components/common/MusicPlayButton/index.tsx
Labels: :hammer:Refactor

#216 feat: 마이페이지 내 추천 목록 더보기 기능
  src/components/common/NoContent/index.tsx
  src/components/mypage/ContentList.tsx
  src/components/mypage/api.ts
  src/components/mypage/post/api.ts
  src/components/mypage/post/useGetMyPostList.ts
  src/pages/mypage/post.tsx
Labels: :sparkles:Feature

#231 refactor: bottom nav 개선
  public/images/bottom-nav/battle-icon-off.svg
  public/images/bottom-nav/feed-icon-off.svg
  public/images/bottom-nav/main-icon-off.svg
  public/images/bottom-nav/mypage-icon-off.svg
  public/images/bottom-nav/share-icon-off.svg
  src/components/common/BottomNav.tsx
  src/components/common/BottomNav/index.tsx
Labels: :hammer:Refactor

#247 chore: useAuth에 getAccessToken 추가
  src/components/login/useAuth.ts
Labels: ✏️Chore

#242 refactor: 배틀 관련 공통 컴포넌트 리팩토링
  src/components/battle/Detail/Battle/Finished.tsx
  src/components/battle/Detail/Battle/index.tsx
  src/components/battle/Detail/BattleMusic/Finished.tsx
  src/components/battle/Detail/BattleMusic/index.tsx
  src/components/battle/Detail/types.ts
  src/components/battle/types.ts
  src/components/battle/voteResult/index.tsx
  src/components/post/api.ts
  src/pages/test/index.tsx
Labels: :hammer:Refactor

#248 feat: 메인 화면 구성
  src/components/common/BottomNav.tsx
  src/components/main/GenreTop10Post/index.tsx
  src/components/ranking/api.ts
  src/components/ranking/index.tsx
  src/pages/index.tsx
  src/pages/ranking/index.tsx
Labels: :sparkles:Feature

#254 fix: 검색 문제 해결
  src/components/post/api.ts
Labels: :lady_beetle:BugFix

#257 chore: meta tag 추가
  public/images/og-image.svg
  src/pages/_document.tsx
Labels: ✏️Chore

#260 feat: 유저 페이지 추가
  src/components/common/BottomNav.tsx
  src/components/common/skeleton/Circle.tsx
  src/components/mypage/battle/useGetMyBattleList.ts
  src/components/post/detail/index.tsx
  src/components/post/detail/types.ts
  src/components/profile/ContentList.tsx
  src/components/profile/ResultCard.tsx
  src/components/profile/UserContent.tsx
  src/components/profile/UserHeader.tsx
  src/components/profile/api.ts
  src/components/profile/battle/api.ts
  src/components/profile/battle/useGetMyBattleList.ts
  src/components/profile/hooks/useGetUserProfile.ts
  src/components/profile/post/api.ts
  src/components/profile/post/useGetMyPostList.ts
  src/components/profile/types.ts
  src/components/ranking/RankingCard.tsx
  src/components/ranking/api.ts
  src/pages/profile/battle/index.tsx
  src/pages/profile/index.tsx
  src/pages/profile/post.tsx
Labels: :sparkles:Feature

#251 refactor: 대결 투표 페이지 코드 재구성
  src/components/battle/Detail/Battle/index.tsx
  src/components/battle/Detail/BattleMusic/index.tsx
  src/components/battle/voteResult/index.tsx
  src/components/common/AlbumPoster/index.tsx
  src/pages/battle/detail.tsx
  src/pages/battle/short.tsx
  src/pages/test/index.tsx
Labels: :hammer:Refactor

#244 feat: 대결 신청 페이지 관련한 Error 처리
  src/components/common/ImageButtons/LikeButton.tsx
  src/components/common/RecommendationPost/index.tsx
  src/components/post/battle/api.ts
  src/components/post/battle/index.tsx
  src/components/post/battle/mybattleList/api.ts
  src/components/post/battle/mybattleList/index.tsx
  src/components/post/battle/types.ts
Labels: :sparkles:Feature

#252 refactor: 폴더명 컨벤션에 맞춰 수정 (components/Detail -> components/detail)
  src/components/battle/detail/Battle/Finished.tsx
  src/components/battle/detail/Battle/index.tsx
  src/components/battle/detail/BattleMusic/Finished.tsx
  src/components/battle/detail/BattleMusic/index.tsx
  src/components/battle/detail/types.ts
  src/pages/battle/detail.tsx
  src/pages/battle/short.tsx
  src/pages/test/index.tsx
Labels: :hammer:Refactor

#265 refactor: noContent 넣기
  src/components/battle/detail/Battle/index.tsx
  src/components/battle/select/index.tsx
  src/components/post/index.tsx
  src/pages/post/index.tsx
  src/pages/profile/post.tsx
Labels: :hammer:Refactor

#268 feat: 유저프로필 더보기 API 연결
  src/components/profile/ContentList.tsx
  src/components/profile/post/api.ts
  src/components/profile/post/useGetMyPostList.ts
  src/pages/profile/battle/index.tsx
  src/pages/profile/post.tsx
Labels: :sparkles:Feature

#234 feat: 장르별 좋아요 순으로 정렬 된 추천 글 버그 해결 및 기능 추가
  src/components/main/GenreTop10Post/DeskTopPosts.tsx
  src/components/main/GenreTop10Post/MobilePosts.tsx
  src/components/main/GenreTop10Post/api.ts
  src/hooks/useCheckMobile.ts
  src/pages/index.tsx
Labels: :lady_beetle:BugFix, :sparkles:Feature

#271 fix: 리스트 없는 경우 더보기 버튼 안보이게 처리
  src/components/profile/ContentList.tsx
  src/components/profile/UserContent.tsx
Labels: :lady_beetle:BugFix

#267 fix: 안쓰는 폴더 정리 및 의존성 제거
  src/components/battle/detail/useGetBattle.tsx
  src/components/battle/select/hooks/useVoteSelect.ts
  src/pages/battle/detail.tsx
  src/pages/battle/short.tsx
  src/pages/test/index.tsx
Labels: :lady_beetle:BugFix

#274 fix: 뒤로가기 없애기
  src/components/common/Header/index.tsx
  src/pages/battle/list.tsx
  src/pages/battle/short.tsx
Labels: :hammer:Refactor

#277 fix: api 교체
  src/components/post/api.ts
Labels: :lady_beetle:BugFix

#270 feat: 메인 랜덤 배틀 get api 연결
  src/components/main/RandomBattle/api.ts
  src/components/main/RandomBattle/index.tsx
  src/pages/index.tsx
Labels: :sparkles:Feature

#281 refactor: 음악 선택 로직 Battle 컴포넌트에 넣기
  src/components/battle/detail/Battle/index.tsx
  src/pages/battle/detail.tsx
  src/pages/battle/short.tsx
Labels: :hammer:Refactor

#284 chore: 전반적인 스타일 수정
  src/components/battle/detail/BattleMusic/index.tsx
  src/components/common/RecommendationPost/index.tsx
  src/components/post/SearchMusics/MusicList.tsx
  src/components/post/battle/mybattleList/index.tsx
  src/components/post/detail/index.tsx
  src/pages/post/index.tsx
Labels: ✏️Chore

#255 feat: 추천 글 상세페이지 좋아요 기능 구현
  package.json
  src/components/common/ImageButtons/LikeButton.tsx
  src/components/common/RecommendationPost/index.tsx
  src/components/post/detail/api.ts
  src/components/post/detail/index.tsx
  src/components/post/detail/types.ts
  src/hooks/useLike.ts
  src/pages/_app.tsx
  yarn.lock
Labels: :sparkles:Feature

#278 fix: 대결 신청 페이지 및 대결 쇼츠에서 한개의 노래만 play 되도록 수정
  src/components/battle/detail/Battle/index.tsx
  src/components/battle/detail/BattleMusic/index.tsx
  src/components/common/MusicPlayButton/index.tsx
  src/components/post/battle/index.tsx
  src/hooks/useBattleMusicPlay.ts
Labels: :lady_beetle:BugFix

#283 fix: 뒤로가기 버튼 클릭 시 의도하지 않는 페이지로 이동하는 문제 해결
  src/components/post/battle/index.tsx
  src/pages/ranking/index.tsx
Labels: :lady_beetle:BugFix

#285 refactor: 음악 재생 progress bar 움직이게 하기
  src/components/battle/detail/Battle/index.tsx
  src/components/battle/detail/BattleMusic/index.tsx
  src/components/common/MusicPlayButton/index.tsx
  src/components/post/battle/index.tsx
  src/components/post/detail/index.tsx
Labels: :hammer:Refactor

#291 refactor: play 버튼 버그 해결하기
  src/components/battle/detail/Battle/index.tsx
  src/components/battle/detail/BattleMusic/index.tsx
  src/components/common/MusicPlayButton/index.tsx
  src/hooks/useBattleMusicPlay.ts
  src/pages/battle/short.tsx
Labels: :lady_beetle:BugFix

#292 feat: 종료된 대결 상세 페이지 구현 및 대결 상세 페이지 라우팅
  src/components/battle/Card/Finished.tsx
  src/components/battle/Card/index.tsx
  src/components/battle/detail/Battle/Finished.tsx
  src/components/battle/detail/Battle/index.tsx
  src/components/battle/detail/BattleMusic/Finished.tsx
  src/components/battle/detail/BattleMusic/index.tsx
  src/components/battle/detail/BattleMusic/style.ts
  src/components/battle/list/index.tsx
  src/components/battle/types.ts
  src/components/profile/UserContent.tsx
  src/pages/battle/detail.tsx
  src/pages/battle/short.tsx
Labels: :sparkles:Feature

#293 feat: 로그아웃 기능 구현
  src/components/login/useAuth.ts
  src/components/profile/UserHeader.tsx
Labels: :sparkles:Feature

#298 fix: 건너뛰기 수정
  src/components/battle/api.ts
Labels: :lady_beetle:BugFix

#300 feat: 음악 리스트 블랙리스트 만들기
  src/components/post/api.ts
Labels: :sparkles:Feature

#301 chore: 메인 페이지 스타일 수정
  src/components/common/AlbumPoster/index.tsx
  src/components/main/GenreTop10Post/DeskTopPosts.tsx
  src/components/main/GenreTop10Post/MobilePosts.tsx
  src/components/ranking/index.tsx
  src/pages/battle/short.tsx
  src/pages/index.tsx
  src/pages/post/battle/index.tsx
  src/pages/post/searchMusics.tsx
  src/pages/profile/post.tsx
  src/pages/ranking/index.tsx
  src/styles/global.ts
  src/styles/reset.ts
Labels: ✏️Chore

#303 chore: 추천 피드 스타일 수정
  src/components/common/Header/index.tsx
  src/components/common/RecommendationPost/index.tsx
  src/pages/battle/list.tsx
  src/pages/index.tsx
  src/pages/post/index.tsx
Labels: ✏️Chore

#306 chore: post detail 스타일 수정
  src/components/post/detail/index.tsx
  src/components/post/detail/musicInfo/index.tsx
Labels: ✏️Chore

#308 feat: 설문 조사 및 정보 모달 넣기
  public/images/info-icon.svg
  public/images/survey-icon.svg
  src/components/main/Info.tsx
  src/components/main/const.ts
  src/pages/index.tsx
Labels: :sparkles:Feature

#309 chore: 추천 글쓰기 스타일 수정
  src/components/common/Header/SubmitButton.tsx
  src/components/common/Header/index.tsx
  src/components/common/ImageButtons/BattleButton.tsx
  src/components/common/ImageButtons/LikeButton.tsx
  src/components/common/MusicCard/index.tsx
  src/components/common/RecommendationPost/index.tsx
  src/components/common/Toggle/index.tsx
  src/components/post/SearchMusics/MusicList.tsx
  src/components/post/SearchMusics/SearchInput.tsx
  src/components/post/SearchMusics/index.tsx
  src/components/post/create/SelectedMusic.tsx
  src/components/post/create/index.tsx
  src/hooks/useCreatePost.ts
  src/pages/post/create.tsx
Labels: ✏️Chore

#311 chore: 대결 신청 페이지 스타일 수정
  src/components/post/battle/mybattleList/index.tsx
Labels: ✏️Chore

#314 docs: select 폴더 제거
  src/components/battle/select/index.tsx
Labels: :page_with_curl:Docs

#315 feat: 대결 상세 미완 기능 완성
  src/components/battle/detail/Battle/Finished.tsx
  src/components/battle/detail/Battle/index.tsx
  src/components/battle/detail/BattleMusic/Finished.tsx
  src/components/battle/detail/BattleMusic/index.tsx
  src/components/battle/detail/BattleMusic/style.ts
  src/components/common/MusicPlayButton/index.tsx
  src/components/common/skeleton/BattleMusic.tsx
  src/components/post/create/SelectedMusic.tsx
  src/pages/battle/detail.tsx
Labels: :sparkles:Feature

#316 feat: 메인 이런 곡은 어때요 추천 글 없으면 추천 글 없다고 render
  src/components/main/GenreTop10Post/DeskTopPosts.tsx
  src/components/main/GenreTop10Post/MobilePosts.tsx
  src/pages/index.tsx
Labels: :hammer:Refactor

#322 refactor: 애니메이션 재적용
  src/components/battle/detail/BattleMusic/index.tsx
  src/components/battle/detail/BattleMusic/style.ts
  src/components/battle/voteResult/index.tsx
Labels: :hammer:Refactor

#313 refactor: 메인 헤더에 아이콘 관련 수정
  public/images/cancel-icon.svg
  public/images/info-icon.svg
  public/images/survey-icon.svg
  src/components/main/Info.tsx
  src/pages/index.tsx
Labels: :hammer:Refactor

#323 fix: 배틀 상세 관련 레이아웃 버그 Fix
  src/components/battle/detail/Battle/Finished.tsx
  src/components/battle/detail/Battle/index.tsx
  src/components/battle/detail/Battle/style.ts
  src/components/battle/voteResult/index.tsx
  src/pages/battle/detail.tsx
  src/pages/battle/short.tsx
Labels: :lady_beetle:BugFix

#325 feat: 메인 페이지 > 랜덤 배틀 컴포넌트 누르면 대결 상세 페이지로 라우팅
  src/pages/index.tsx
Labels: :sparkles:Feature

#328 feat: 참여한 대결 페이지 필터링
  src/components/profile/UserContent.tsx
  src/components/profile/battle/api.ts
  src/components/profile/battle/useGetMyBattleList.ts
  src/pages/profile/battle/index.tsx
Labels: :sparkles:Feature

#339 chore: battle short NoContent 위치 수정
  src/components/battle/detail/Battle/index.tsx
Labels: ✏️Chore

#341 chore: main NoContent 위치 수정
  src/components/main/GenreTop10Post/DeskTopPosts.tsx
  src/components/main/GenreTop10Post/MobilePosts.tsx
  src/components/profile/UserContent.tsx
Labels: ✏️Chore

#343 fix: 대결 관련 페이지 스타일 문제 수정
  src/pages/battle/list.tsx
  src/pages/profile/battle/index.tsx
Labels: :lady_beetle:BugFix

#344 feat: modal style 수정 및 Toast 생성
  src/components/common/Modal/Confirm.tsx
  src/components/common/Modal/Wrapper.tsx
  src/components/common/Toast.tsx
  src/components/login/AuthRequiredModal.tsx
  src/components/post/battle/mybattleList/index.tsx
  src/hooks/useCreatePost.ts
  src/hooks/useToast.ts
  src/pages/post/create.tsx
Labels: :sparkles:Feature

#345 fix: 유저페이지에서 로그아웃 막기
  src/components/profile/UserHeader.tsx
Labels: :lady_beetle:BugFix

#346 fix: 정지 아이콘 refetch시 유지되는 문제 막기
  src/components/battle/detail/Battle/index.tsx
Labels: :lady_beetle:BugFix

#347 fix: 투표 결과 모달 '돌아가기' 버튼 라우팅 404 에러 고치기
  src/components/battle/voteResult/index.tsx
Labels: :lady_beetle:BugFix

#348 fix: 대결 신청 페이지에서 내 대결 곡 고르기 배경화면 회색 변경 및 플러스 아이콘 render
  src/components/post/battle/index.tsx
  src/components/post/battle/selectMusic/index.tsx
Labels: :lady_beetle:BugFix

#349 refactor: 대결 투표 디자인 틀어진 부분 수정
  src/components/battle/detail/Battle/index.tsx
  src/components/common/skeleton/AlbumPosterSkeleton.tsx
Labels: :hammer:Refactor

#351 fix: 진행종료된 대결 음악 플레이 문제 해결
  src/components/battle/detail/Battle/Finished.tsx
Labels: :lady_beetle:BugFix

#355 chore: 누락된 디자인 추가
  src/components/battle/detail/Battle/style.ts
Labels: ✏️Chore

#358 feat: 자동 로그인 시 유효한 토큰인지 체크
  src/components/login/api.ts
  src/components/login/store.ts
  src/components/login/useAuth.ts
Labels: :sparkles:Feature

#357 fix: 투표 여부 판별 로직 fix
  src/components/battle/detail/Battle/index.tsx
Labels: :lady_beetle:BugFix

#360 refactor: info 예쁘게 바꾸기 & 디자인 수정
  src/components/main/Info.tsx
  src/components/main/const.ts
Labels: :hammer:Refactor

#364 feat: 로고 클릭 시 메인 페이지로 이동하도록
  src/pages/login.tsx
Labels: :sparkles:Feature

#368 chore: 진행 중 대결 없을 때 UI 처리
  src/pages/index.tsx
Labels: ✏️Chore

#371 fix: 내 추천 목록에 마지막 추천글 바텀 Navbar에 의해 가려있는 문제 해결
  src/pages/profile/post.tsx
Labels: :lady_beetle:BugFix

#372 fix: 유저 랭킹페이지에 등록된 유저가 없습니다 짤리는 문제 해결
  src/components/ranking/index.tsx
Labels: :lady_beetle:BugFix

#373 feat: 로그인 한 경우 로그인 페이지 접근 시 메인 페이지로 보내주기
  src/pages/login.tsx
Labels: :sparkles:Feature

#376 refactor: 랭킹에 nocontent 넣기
  src/components/post/create/SelectedMusic.tsx
  src/components/ranking/index.tsx
Labels: :hammer:Refactor

#378 fix: 참여한 대결 리스트 페이지에 memberId query 반영하도록
  src/pages/profile/battle/index.tsx
Labels: :lady_beetle:BugFix

#380 fix: 메인 페이지 레이아웃 버그 fix
  src/pages/index.tsx
Labels: :lady_beetle:BugFix

#381 fix: 메인 bottom에 padding 주기
  src/components/ranking/index.tsx
Labels: :hammer:Refactor

#384 chore: main NoContent 스타일 통일
  src/components/ranking/index.tsx
  src/pages/index.tsx
Labels: ✏️Chore

#385 chore: 파비콘 설정
  public/favicon.ico
Labels: ✏️Chore

#386 chore: GA 측정 위해 GTM 연동
  src/components/googleTagManager/Noscript.tsx
  src/components/googleTagManager/Script.tsx
  src/components/googleTagManager/gtm.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
Labels: ✏️Chore

#387 fix: 로그인 안 한 상태에서 인증 필요한 페이지 접근 시 로그인 모달 띄워주기
  src/components/battle/list/index.tsx
  src/components/post/detail/index.tsx
  src/components/ranking/RankingCard.tsx
  src/pages/index.tsx
Labels: :lady_beetle:BugFix

#390 chore: 대결 투표 수치 조절
  src/pages/battle/detail.tsx
  src/pages/battle/short.tsx
Labels: ✏️Chore

#391 fix: 마이페이지 > 대결권 0개일 때 처리
  src/components/profile/UserHeader.tsx
Labels: :lady_beetle:BugFix

#377 docs: README 수정
  README.md
Labels: :page_with_curl:Docs

#394 feat: 마이페이지 내 좋아요 목록 추가
  src/components/profile/ContentList.tsx
  src/components/profile/UserContent.tsx
  src/components/profile/api.ts
  src/components/profile/likes/useGetMyLikeList.ts
  src/components/profile/post/useGetMyPostList.ts
  src/pages/profile/likes.tsx
Labels: :sparkles:Feature

#402 refactor: create 구조 변경
  src/components/post/create/Inputs.tsx
  src/components/post/create/index.tsx
  src/components/post/create/types.ts
  src/pages/post/create.tsx
Labels: :hammer:Refactor

#403 feat: 음악 검색 결과 유지도록 하기
  src/components/common/BottomNav.tsx
  src/components/post/search/store.ts
  src/pages/post/searchMusics.tsx
Labels: :sparkles:Feature
