Repository prgrms-web-devcourse/Team-6Jeans-Hype-FE, pull requests merged in 2023-02, with the labels that each got.

#4 chore: 프로젝트 초기 세팅
  .eslintrc.json
  .gitignore
  .prettierrc.json
  .vscode/settings.json
  README.md
  next.config.js
  package.json
  public/favicon.ico
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  tsconfig.json
  yarn.lock
Labels: :gear:Setting

#6 docs: PR 닫으면 이슈 자동으로 닫히도록 PR 템플릿 수정
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: :page_with_curl:Docs

#9 chore: emotion 설치
  package.json
  yarn.lock
Labels: :gear:Setting

#13 chore: axios, lodash 설치
  package.json
  yarn.lock
Labels: :gear:Setting

#10 chore: 빌드 테스트 workflow 추가
  .github/workflows/build-test.yml
Labels: :gear:Setting

#19 feat: 추천 리스트 생성
  .gitignore
  .vscode/settings.json
  package.json
  src/components/common/Toggle.tsx
  src/components/common/skeleton/Base.tsx
  src/components/common/skeleton/Box.tsx
  src/components/common/skeleton/MusicList.tsx
  src/components/post/create/index.tsx
  src/components/post/create/musicSearcher/MusicList.tsx
  src/components/post/create/musicSearcher/SearchInputs.tsx
  src/components/post/create/musicSearcher/SelectedMusic.tsx
  src/components/post/create/musicSearcher/index.tsx
  src/components/post/create/types.ts
  src/hooks/useCreatePost.ts
  src/hooks/useMusicList.ts
  src/hooks/useToggle.ts
  src/pages/index.tsx
  src/pages/post/create.tsx
  src/utils/apis/music.ts
  yarn.lock
Labels: :sparkles:Feature

#25 chore: eslint-plugin-simple-import-sort 추가
  .eslintrc.json
  .vscode/settings.json
  package.json
  yarn.lock
Labels: :gear:Setting

#26 feat: 추천 피드 생성 장르 필드 추가, 페이지 분리
  .prettierrc.json
  public/images/search.png
  src/components/post/SearchMusics/MusicList.tsx
  src/components/post/SearchMusics/SearchInput.tsx
  src/components/post/SearchMusics/index.tsx
  src/components/post/SearchMusics/types.tsx
  src/components/post/create/SelectedMusic.tsx
  src/components/post/create/index.tsx
  src/components/post/create/musicSearcher/MusicList.tsx
  src/components/post/create/musicSearcher/SearchInputs.tsx
  src/components/post/create/musicSearcher/SelectedMusic.tsx
  src/components/post/create/musicSearcher/index.tsx
  src/components/post/create/types.ts
  src/constants/genreData.ts
  src/hooks/useCreatePost.ts
  src/hooks/useMusicList.ts
  src/hooks/useSearchMusics.ts
  src/pages/index.tsx
  src/pages/post/SearchMusics.tsx
  src/utils/apis/music.ts
Labels: :sparkles:Feature

#27 feat: 로그인 페이지 마크업
  next.config.js
  package.json
  public/images/google-logo.svg
  public/images/image-logo.svg
  public/images/letter-logo.svg
  src/pages/_app.tsx
  src/pages/login.tsx
  src/styles/global.ts
  src/styles/reset.ts
  yarn.lock
Labels: :sparkles:Feature

#17 feat: 추천 리스트 조회
  src/components/post/api.ts
  src/components/post/index.tsx
  src/components/post/types.ts
  src/pages/post/index.tsx
Labels: :sparkles:Feature

#21 feat: 추천 글 상세 조회
  src/components/post/detail/api.ts
  src/components/post/detail/index.tsx
  src/components/post/detail/musicInfo/index.tsx
  src/components/post/detail/types.ts
  src/components/post/index.tsx
  src/pages/post/detail/index.tsx
Labels: :sparkles:Feature

#36 chore: axiosInstance 생성
  src/api/index.ts
Labels: :gear:Setting

#43 feat: 추천 피드 생성 마크업
  public/images/post-cancel-button.svg
  public/images/search-icon.svg
  public/images/search.png
  public/images/translucent-logo.svg
  src/components/common/AlbumPoster/index.tsx
  src/components/common/Genres/index.tsx
  src/components/common/Toggle/index.tsx
  src/components/post/SearchMusics/MusicList.tsx
  src/components/post/SearchMusics/SearchInput.tsx
  src/components/post/SearchMusics/index.tsx
  src/components/post/create/SelectedMusic.tsx
  src/components/post/create/index.tsx
  src/constants/color.ts
  src/hooks/useCreatePost.ts
  src/pages/post/searchMusics.tsx
  src/styles/global.ts
Labels: :sparkles:Feature

#38 fix: 글로벌 배경 색상 변경
  src/styles/global.ts
Labels: :lady_beetle:BugFix

#31 feat: 대결 신청 기능
  src/components/post/battle/api.ts
  src/components/post/battle/index.tsx
  src/components/post/battle/musicinfo/index.tsx
  src/components/post/battle/mybattleList/api.ts
  src/components/post/battle/mybattleList/index.tsx
  src/components/post/battle/types.ts
  src/hooks/useConfirmModal.ts
  src/pages/post/battle/index.tsx
  src/pages/post/battle/mybattlelist/index.tsx
Labels: :sparkles:Feature

#39 feat: 추천 피드 리스트 filter 기능 구현
  src/components/common/Battles.tsx
  src/components/post/api.ts
  src/components/post/index.tsx
Labels: :sparkles:Feature

#41 feat: 추천 피드 마크업
  public/images/down-arrow.png
  public/images/fire.png
  public/images/full-heart.png
  public/images/heart.png
  src/components/post/index.tsx
Labels: :sparkles:Feature

#53 feat: 대결 신청 페이지 마크업
  public/images/plus-music.png
  src/components/post/battle/index.tsx
  src/components/post/battle/musicinfo/index.tsx
  src/components/post/battle/mybattleList/index.tsx
Labels: :sparkles:Feature

#56 feat: bottom-nav 제작
  public/images/bottom-nav/battle-icon-off.svg
  public/images/bottom-nav/battle-icon.svg
  public/images/bottom-nav/feed-icon-off.svg
  public/images/bottom-nav/feed-icon.svg
  public/images/bottom-nav/main-icon-off.svg
  public/images/bottom-nav/main-icon.svg
  public/images/bottom-nav/mypage-icon-off.svg
  public/images/bottom-nav/mypage-icon.svg
  public/images/bottom-nav/share-icon-off.svg
  public/images/bottom-nav/share-icon.svg
  src/components/common/BottomNav/index.tsx
  src/pages/index.tsx
  src/pages/post/create.tsx
Labels: :sparkles:Feature

#61 feat: 구글 로그인 구현
  src/components/login/GoogleLoginButton.tsx
  src/components/login/api.ts
  src/components/login/constants.ts
  src/pages/auth/callback/google.tsx
  src/pages/login.tsx
Labels: :sparkles:Feature

#66 refactor: env 변수 네이밍 변경 적용
  src/components/post/api.ts
Labels: :hammer:Refactor

#71 feat: 배틀 관련 음악 정보 공통 컴포넌트
  public/images/plus-music.png
  public/images/plus-music.svg
  src/components/common/BattleMusicInfo/index.tsx
  src/components/post/battle/index.tsx
Labels: :sparkles:Feature
